sql:
  #The name of the database to be used
  database:
  ip:
  port:
  username:
  password:


kit:
  inventory:
    1:
    2:
    3:
    4:
    5:
    6:
    7:
    8:
    9:
  armor:
    helmet:
    chest:
    legs:
    boots:
  #Write enchants with sub-categories on the item number or armor name
  #
  # 1:
  #   asdfasdf: ARROW_FIRE
  #   zxcqra1g: ARROW_INFINITE
  #
  #The field name doesn't matter
  enchants:
    1:
    2:
    3:
    4:
    5:
    6:
    7:
    8:
    9:
    helmet:
    chest:
    legs:
    boots: