sql:
  database:
  ip:
  port:
  username:
  password:
kits:
  Def:
    inventory:
      1:
      2:
      3:
      4:
      5:
      6:
      7:
      8:
      9:
    armor:
      helmet:
      chest:
      legs:
      boots: