name: VersusArena
main: bourg.austin.VersusArena.VersusArena
version: 1.0.0
commands:
  versus:
    description: 'The root command for the Versus Arena Plugin'
    usage: '/<command> subject action'
    permission-message: 'You don''t have <permission>'
  logstatus:
    description: shit
    usage: lol
    permission-message: 'Delete this, lol'
permissions:
  'pairspvp.*':
    description: 'Gives access to everything'
    default: op
    children:
      pairspvp.go: true
      'pairspvp.nexus.*': true
      'pairspvp.arena.*': true
      'pairspvp.config.*': true
      'pairspvp.rating.*': true
  pairspvp.go:
    description: 'Allows the use of the /versus command to go to the nexus'
    default: true
  pairspvp.select:
    description: 'Allows a player to select a block for use with other commands'
    default: false
  'pairspvp.nexus.*':
    description: 'Allows full control over nexus related commands'
    default: op
    children:
      pairspvp.nexus.delete: true
      pairspvp.nexus.set: true
      pairspvp.nexus.sign: true
  pairspvp.nexus.delete:
    description: 'Allows the use of the /versus nexus delete command'
    default: op
  pairspvp.nexus.set:
    description: 'Allows the use of the /versus nexus set command'
    children:
      pairspvp.select: true
    default: op
  pairspvp.nexus.sign:
    description: 'Allows the user to place signs with /versus as the first line in order to go to arena.'
    default: op
  'pairspvp.arena.*':
    description: 'Allows full control over arena related commands'
    children:
      pairspvp.arena.modify: true
      pairspvp.arena.view: true
    default: op
  pairspvp.arena.modify:
    description: 'Allows the use of any commands that modify arenas'
    children:
      pairspvp.arena.make: true
      pairspvp.arena.delete: true
      pairspvp.arena.setspawn: true
      pairspvp.arena.setdeath: true
      pairspvp.arena.setfacing: true
    default: op
  pairspvp.arena.view:
    description: 'Allows the use of any commands that allow viewing of arenas and details'
    children:
      pairspvp.arena.list: true
      pairspvp.arena.details: true
    default: op
  pairspvp.arena.make:
    description: 'Allows the use of the /versus arena make <name> command'
    default: op
  pairspvp.arena.delete:
    description: 'Allows the use of the /versus arena delete <name> command'
    default: op
  pairspvp.arena.setfacing:
    description: 'Allows the use of the /versus arena setfacing <name> <team> <player> command'
    default: op
  pairspvp.arena.list:
    description: 'Allows the use of the /versus arena list command'
    default: op
  pairspvp.arena.details:
    description: 'Allows the use of the /versus arena details <name> command'
    default: op
  pairspvp.arena.setspawn:
    description: 'Allows the use of the /versus arena setdeath <name> command'
    default: op
    children:
      pairspvp.select: true
  'pairspvp.config.*':
    description: 'Allows the use of any commands relating to the config file.'
    default: op
    children:
      pairspvp.config.save: true
      pairspvp.config.load: true
  pairspvp.config.save:
    description: 'Allows the use of the /versus config save command.'
    default: op
  pairspvp.config.load:
    description: 'Allows the use of the /versus config load command. This shouldn''t be used outside of debugging.'
    default: op
  'pairspvp.rating.*':
    description: 'Allows full control of rating signs'
    default: op
    children:
      pairspvp.rating.make: true
      pairspvp.rating.break: true
  pairspvp.rating.make:
    description: 'Allows the player to make rating signs'
    default: op
  pairspvp.rating.break:
    description: 'Allows the player to break rating signs'
    default: op